'use strict';
const M=SlideModel,$=id=>document.getElementById(id);
document.head.append(Object.assign(document.createElement('style'),{textContent:M.slideCSS}));
let deck=M.blank(),page=0,selected=null,scale=1,undo=[],redo=[],db=null,saveQueue=Promise.resolve(),pending=0,storageFailed=false,saveGeneration=0;
const revisions=new Map(),blocked=new Set();
let toastTimer,replaceImage=false,drag=null;
const slide=()=>deck.slides[page],item=()=>slide().elements.find(e=>e.id===selected);
function notify(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,7000);}
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function filename(ext){return (deck.title.replace(/[\\/:*?"<>|]/g,'-').slice(0,100)||'課程')+ext;}
async function database(){return new Promise((resolve,reject)=>{const req=indexedDB.open('course-slide-editor',1);req.onupgradeneeded=()=>req.result.createObjectStore('decks');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);req.onblocked=()=>reject(Error('請關閉舊版編輯器分頁後重試。'));});}
function read(key){return new Promise((resolve,reject)=>{const r=db.transaction('decks').objectStore('decks').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function persist(snapshot){return new Promise((resolve,reject)=>{
 if(!db||blocked.has(snapshot.id)){reject(Error('無法自動保存，請下載課程檔備份。'));return;}
 const tx=db.transaction('decks','readwrite'),store=tx.objectStore('decks'),r=store.get(snapshot.id);let revision,error;
 r.onsuccess=()=>{const current=r.result?.revision||0;if(current!==(revisions.get(snapshot.id)||0)){blocked.add(snapshot.id);error=Error('另一分頁已更新此課程。請先下載本頁課程檔，再重新開啟。');tx.abort();return;}
 revision=current+1;store.put({revision,deck:snapshot},snapshot.id);store.put(snapshot.id,'active');};
 tx.oncomplete=()=>{revisions.set(snapshot.id,revision);resolve();};tx.onabort=()=>reject(error||tx.error||Error('保存未完成。'));tx.onerror=()=>{};
 });}
function saveLocal(){if(window.CourseWorkflow){CourseWorkflow.reconcile(deck);deck.lessonPackage.title=deck.title;}window.CourseUI?.render();const generation=++saveGeneration;if(JSON.stringify(deck).length>50000000){storageFailed=true;$('save-status').textContent='課程過大 · 請減少圖片';notify('課程超過 50 MB。請移除過大的圖片後保存。');return Promise.resolve();}const snapshot=M.clone(deck);pending++;$('save-status').textContent='儲存中…';
 saveQueue=saveQueue.then(()=>persist(snapshot)).then(()=>{if(generation===saveGeneration)storageFailed=false;}).catch(e=>{storageFailed=true;notify(e.message+' 可使用「下載課程檔」保留所有修改。');}).finally(()=>{pending--;$('save-status').textContent=storageFailed?'尚未保存 · 請下載備份':pending?'儲存中…':'已儲存於此瀏覽器';});return saveQueue;}
function record(before){if(before===JSON.stringify(deck))return;undo.push(before);while(undo.length>1&&(undo.length>30||undo.reduce((n,s)=>n+s.length,0)>20000000))undo.shift();redo=[];$('undo').disabled=!undo.length;$('redo').disabled=true;saveLocal();}
function change(fn){const before=JSON.stringify(deck);fn();record(before);render();}
function undoRedo(back){const src=back?undo:redo,dst=back?redo:undo;if(!src.length)return;dst.push(JSON.stringify(deck));deck=JSON.parse(src.pop());page=Math.min(page,deck.slides.length-1);selected=null;saveLocal();render();}
function markSelection(){for(const n of $('stage').querySelectorAll('.slide-element')){const e=slide().elements.find(e=>e.id===n.dataset.id);n.classList.toggle('selected',e.id===selected);n.querySelector('.resize-handle')?.remove();if(e.id===selected&&!e.locked){const h=document.createElement('span');h.className='resize-handle';n.append(h);}}}
function select(id){selected=id;markSelection();inspector();}
function fit(){const area=document.querySelector('.workspace');scale=Math.max(.15,Math.min(1,(area.clientWidth-48)/960,(innerHeight-290)/540));$('stage-wrap').style.width=960*scale+'px';$('stage-wrap').style.height=540*scale+'px';$('stage').style.transform='scale('+scale+')';fitPresent();}
function render(){page=M.clamp(page,0,deck.slides.length-1);$('deck-title').value=deck.title;$('page-label').textContent=(page+1)+' / '+deck.slides.length;
 $('undo').disabled=!undo.length;$('redo').disabled=!redo.length;$('delete-slide').disabled=deck.slides.length===1;$('slide-up').disabled=page===0;$('slide-down').disabled=page===deck.slides.length-1;
 const list=$('slide-list');list.replaceChildren();deck.slides.forEach((s,i)=>{const b=document.createElement('button');b.className='thumb'+(i===page?' active':'');b.setAttribute('aria-label','第 '+(i+1)+' 頁：'+s.title);b.setAttribute('aria-current',i===page?'page':'false');
 const mini=document.createElement('div');mini.className='mini';const canvas=document.createElement('div');canvas.className='slide-canvas';M.paint(s,canvas);mini.append(canvas);
 const label=document.createElement('span');label.className='thumb-label';label.textContent=(i+1)+'  '+s.title;b.append(mini,label);b.onclick=()=>{page=i;selected=null;render();};list.append(b);});
 renderStage();inspector();fit();window.CourseUI?.render();try{window.history.replaceState(null,'','#'+slide().id);}catch{}}
function renderStage(){const stage=$('stage');M.paint(slide(),stage);for(const n of stage.querySelectorAll('.slide-element')){const e=slide().elements.find(x=>x.id===n.dataset.id);n.tabIndex=0;n.setAttribute('role','group');n.setAttribute('aria-label',e.type+'：'+e.text.slice(0,60));n.classList.toggle('locked',e.locked);
 if(e.id===selected){n.classList.add('selected');if(!e.locked){const h=document.createElement('span');h.className='resize-handle';h.setAttribute('aria-hidden','true');n.append(h);}}
 n.onfocus=()=>{selected=e.id;markSelection();inspector();};n.ondblclick=()=>{if(e.type==='image'||e.type==='shape')return;select(e.id);const target=$('stage').querySelector('[data-id="'+e.id+'"] .element-text');const before=JSON.stringify(deck);target.contentEditable='true';target.focus();
 target.textContent=e.text;const range=document.createRange();range.selectNodeContents(target);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);
 target.onpaste=ev=>{ev.preventDefault();document.execCommand('insertText',false,ev.clipboardData.getData('text/plain'));};
 target.oninput=()=>{e.text=target.innerText;saveLocal();};target.onblur=()=>{record(before);render();};};
 }
 requestAnimationFrame(()=>{let count=0;for(const n of stage.querySelectorAll('.element-text'))if(n.scrollHeight>n.clientHeight+2||n.scrollWidth>n.clientWidth+2)count++;$('overflow').textContent=count?'有 '+count+' 個文字框可能放不下。請放大文字框或拆頁，避免內容被裁切。':'';});}
function inspector(){const s=slide(),e=item();$('slide-title').value=s.title;$('source').value=s.source;$('slide-bg').value=s.background;$('notes').value=s.notes;$('element-controls').hidden=!e;$('no-selection').hidden=!!e;$('selected-kind').textContent=e?({text:'文字',image:'圖片',shape:'色塊',flashcard:'翻牌',reveal:'答案'})[e.type]:'投影片';
 if(!e)return;$('background').parentElement.hidden=['text','image'].includes(e.type);for(const k of ['fontSize','align','color','bold'])$(k).disabled=e.type==='image';for(const k of ['text','x','y','w','h','fontSize','align','color','background'])$(k).value=e[k];$('back-text').value=e.backText;$('bold').checked=e.bold;$('locked').checked=e.locked;$('back-label').hidden=!['flashcard','reveal'].includes(e.type);$('replace-image').hidden=e.type!=='image';for(const k of ['x','y','w','h','center-x','center-y'])$(k).disabled=e.locked;}
$('stage').addEventListener('pointerdown',ev=>{if(ev.button!==0||ev.target.isContentEditable)return;const n=ev.target.closest('.slide-element');if(!n){select(null);return;}const resize=ev.target.classList.contains('resize-handle');selected=n.dataset.id;const e=item();if(e.locked){select(e.id);$('stage').focus({preventScroll:true});return;}
 drag={id:e.id,pointer:ev.pointerId,startX:ev.clientX,startY:ev.clientY,x:e.x,y:e.y,w:e.w,h:e.h,resize,before:JSON.stringify(deck)};ev.preventDefault();markSelection();inspector();$('stage').focus({preventScroll:true});});
$('stage').addEventListener('pointermove',ev=>{if(!drag||drag.pointer!==ev.pointerId)return;if(Math.abs(ev.clientX-drag.startX)+Math.abs(ev.clientY-drag.startY)<3)return;if(!$('stage').hasPointerCapture(ev.pointerId))$('stage').setPointerCapture(ev.pointerId);const e=item(),dx=(ev.clientX-drag.startX)/scale,dy=(ev.clientY-drag.startY)/scale,snap=v=>$('snap').checked?Math.round(v/5)*5:Math.round(v);
 if(drag.resize){e.w=M.clamp(snap(drag.w+dx),20,960-e.x);e.h=M.clamp(snap(drag.h+dy),20,540-e.y);}else{e.x=M.clamp(snap(drag.x+dx),0,960-e.w);e.y=M.clamp(snap(drag.y+dy),0,540-e.h);
 if($('snap').checked&&Math.abs(e.x+e.w/2-480)<7)e.x=480-e.w/2;if($('snap').checked&&Math.abs(e.y+e.h/2-270)<7)e.y=270-e.h/2;}
 $('stage').querySelectorAll('.guide-v,.guide-h').forEach(n=>n.remove());if(!drag.resize){for(const [cls,near] of [['guide-v',Math.abs(e.x+e.w/2-480)<1],['guide-h',Math.abs(e.y+e.h/2-270)<1]])if(near){const g=document.createElement('div');g.className=cls;$('stage').append(g);}}
 const n=$('stage').querySelector('[data-id="'+e.id+'"]');Object.assign(n.style,{left:e.x+'px',top:e.y+'px',width:e.w+'px',height:e.h+'px'});});
function endDrag(ev){if(!drag||drag.pointer!==ev.pointerId)return;const before=drag.before;drag=null;if(before!==JSON.stringify(deck)){record(before);render();}}
window.addEventListener('pointerup',endDrag);$('stage').addEventListener('pointercancel',ev=>{if(drag){deck=JSON.parse(drag.before);drag=null;render();}});
for(const key of ['text','x','y','w','h','fontSize','align','color','background','bold','locked'])$(key).onchange=()=>{if(!item())return;change(()=>{const e=item();if(['x','y','w','h','fontSize'].includes(key)){const v=Number($(key).value);if(!Number.isFinite(v))return;e[key]=v;e.w=M.clamp(e.w,20,960);e.h=M.clamp(e.h,20,540);e.x=M.clamp(e.x,0,960-e.w);e.y=M.clamp(e.y,0,540-e.h);e.fontSize=M.clamp(e.fontSize,8,150);}else e[key]=['bold','locked'].includes(key)?$(key).checked:$(key).value;});};
$('back-text').onchange=()=>item()&&change(()=>item().backText=$('back-text').value);
for(const [control,key] of [['text','text'],['back-text','backText']])$(control).oninput=()=>{if(!item())return;const before=JSON.stringify(deck);item()[key]=$(control).value;record(before);renderStage();$('undo').disabled=!undo.length;$('redo').disabled=!redo.length;};
for(const [control,key] of [['slide-title','title'],['source','source'],['notes','notes']])$(control).oninput=()=>{const before=JSON.stringify(deck);slide()[key]=$(control).value;record(before);renderStage();};
$('deck-title').oninput=()=>{const before=JSON.stringify(deck);deck.title=$('deck-title').value.slice(0,500)||'未命名課程';record(before);};

$('deck-title').onchange=()=>change(()=>deck.title=$('deck-title').value.slice(0,500)||'未命名課程');
for(const [control,key] of [['slide-title','title'],['source','source'],['slide-bg','background'],['notes','notes']])$(control).onchange=()=>change(()=>slide()[key]=$(control).value);
$('undo').onclick=()=>undoRedo(true);$('redo').onclick=()=>undoRedo(false);
document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>change(()=>{if(slide().elements.length>=200)return notify('每頁最多 200 個物件。');const e=M.element(b.dataset.add);if(e.type==='shape'){e.text='';e.background='#dcece5';e.w=250;e.h=180;}if(e.type==='flashcard'){e.text='正面问题';e.backText='完整句答案';e.align='center';e.h=180;}if(e.type==='reveal'){e.text='________';e.backText='完整句答案';}slide().elements.push(e);selected=e.id;}));
function remove(){if(!item())return;change(()=>{slide().elements=slide().elements.filter(e=>e.id!==selected);selected=null;});}
$('remove').onclick=remove;$('duplicate').onclick=()=>item()&&change(()=>{if(slide().elements.length>=200)return notify('每頁最多 200 個物件。');const e=M.clone(item());e.id=M.id();e.x=M.clamp(e.x+15,0,960-e.w);e.y=M.clamp(e.y+15,0,540-e.h);slide().elements.push(e);selected=e.id;});
for(const [button,fn] of [['center-x',e=>e.x=(960-e.w)/2],['center-y',e=>e.y=(540-e.h)/2],['front',e=>{slide().elements=slide().elements.filter(x=>x!==e);slide().elements.push(e);}],['back',e=>{slide().elements=slide().elements.filter(x=>x!==e);slide().elements.unshift(e);}]])$(button).onclick=()=>item()&&change(()=>fn(item()));
$('add-slide').onclick=()=>change(()=>{if(deck.slides.length>=500)return notify('每課最多 500 頁。');deck.slides.splice(page+1,0,M.slide());page++;selected=null;});
$('copy-slide').onclick=()=>change(()=>{if(deck.slides.length>=500)return;const s=M.clone(slide());s.id=M.id();s.title+='（副本）';s.elements.forEach(e=>e.id=M.id());deck.slides.splice(page+1,0,s);page++;selected=null;});
$('delete-slide').onclick=()=>{if(deck.slides.length>1&&confirm('刪除這張投影片？可使用復原還原。'))change(()=>{deck.slides.splice(page,1);page=Math.min(page,deck.slides.length-1);selected=null;});};
for(const [button,delta] of [['slide-up',-1],['slide-down',1]])$(button).onclick=()=>{if(page+delta<0||page+delta>=deck.slides.length)return;change(()=>{const s=deck.slides.splice(page,1)[0];page+=delta;deck.slides.splice(page,0,s);});};
async function switchDeck(candidate,revision=0){const checked=CourseWorkflow.migrate(M.validate(candidate));if(pending)await saveQueue;if(storageFailed&&!confirm('目前課程尚未保存。建議先下載課程檔。仍要開啟另一課？'))return;deck=checked;page=0;selected=null;undo=[];redo=[];revisions.set(deck.id,revision);blocked.delete(deck.id);saveLocal();render();}
$('new').onclick=()=>{if(confirm('建立新課程？目前課程請先下載課程檔，以便之後再開啟。'))switchDeck(M.blank());};
$('open').onclick=async()=>{const list=$('recent-list');list.replaceChildren();if(db){try{await saveQueue;const records=await new Promise((resolve,reject)=>{const r=db.transaction('decks').objectStore('decks').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});for(const record of records.filter(r=>r&&r.deck)){const b=document.createElement('button');b.textContent=record.deck.title+' · '+record.deck.slides.length+' 頁';b.onclick=async()=>{const fresh=await read(record.deck.id);$('recent').close();await switchDeck(fresh.deck,fresh.revision);};list.append(b);}}catch(e){notify('讀取最近課程失敗，可改開啟已下載的課程檔。');}}if(!list.children.length)list.textContent='還沒有儲存的課程。';$('recent').showModal();};$('open-file').onclick=()=>{$('recent').close();$('file').click();};$('close-recent').onclick=()=>$('recent').close();$('file').onchange=async ev=>{const f=ev.target.files[0];ev.target.value='';if(!f)return;try{if(f.size>50000000)throw Error('課程檔需小於 50 MB。');const d=M.validate(JSON.parse(await f.text()));d.id=M.id();await switchDeck(d);}catch(e){notify(e.message);}};
$('save').onclick=()=>{document.activeElement?.blur();try{download(JSON.stringify(M.validate(deck),null,2),filename('.slides.json'),'application/json');notify('課程檔已下載。再次開啟可繼續編輯。');}catch(e){notify(e.message);}};
$('add-image').onclick=()=>{replaceImage=false;$('image-file').click();};$('replace-image').onclick=()=>{replaceImage=true;$('image-file').click();};
$('image-file').onchange=async ev=>{const f=ev.target.files[0];ev.target.value='';if(!f)return;const target=replaceImage?selected:null,slideId=slide().id;try{if(!['image/png','image/jpeg','image/webp','image/gif'].includes(f.type)||f.size>10000000)throw Error('請選擇 10 MB 以內的 PNG、JPG、WebP 或 GIF。');const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('讀取圖片失敗。'));r.readAsDataURL(f);});const image=new Image();image.src=src;await image.decode();if(slide().id!==slideId)throw Error('投影片已切換，請在目標頁重新加入圖片。');change(()=>{if(target){const e=slide().elements.find(e=>e.id===target);if(e)e.src=src;}else{if(slide().elements.length>=200)return notify('每頁最多 200 個物件。');const w=Math.min(480,image.naturalWidth),h=Math.min(300,w*image.naturalHeight/image.naturalWidth),width=h*image.naturalWidth/image.naturalHeight;const e=M.element('image',{src,text:f.name,w:Math.max(20,width),h:Math.max(20,h)});slide().elements.push(e);selected=e.id;}});}catch(e){notify(e.message);}};
function fitPresent(){if(!$('presenter').open)return;const s=Math.min(innerWidth/960,(innerHeight-65)/540);$('present-stage').style.transform='scale('+s+')';$('present-wrap').style.width=960*s+'px';$('present-wrap').style.height=540*s+'px';}
let presenting=0;
function showPresent(){M.paint(deck.slides[presenting],$('present-stage'),true);$('present-count').textContent=(presenting+1)+' / '+deck.slides.length;$('prev').disabled=presenting===0;$('next').disabled=presenting===deck.slides.length-1;fitPresent();}
$('present').onclick=()=>{document.activeElement?.blur();if(!CourseUI.allowRelease())return;presenting=page;$('presenter').showModal();showPresent();};
$('fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen?.().catch(()=>notify('瀏覽器未允許全螢幕，可繼續使用放映視窗。'));};$('presenter').addEventListener('close',()=>{if(document.fullscreenElement)document.exitFullscreen();});$('exit-present').onclick=()=>$('presenter').close();$('prev').onclick=()=>{presenting=Math.max(0,presenting-1);showPresent();};$('next').onclick=()=>{presenting=Math.min(deck.slides.length-1,presenting+1);showPresent();};
$('print').onclick=()=>{document.activeElement?.blur();if(!CourseUI.allowRelease())return;$('print-area')?.remove();const area=document.createElement('div');area.id='print-area';for(const s of deck.slides){const n=document.createElement('div');n.className='slide-canvas print-slide';M.paint(s,n);area.append(n);}document.body.append(area);window.print();};
$('export').onclick=()=>{document.activeElement?.blur();if(!CourseUI.allowRelease())return;try{download(exportHTML(M.validate(deck)),filename('.html'),'text/html');notify('已匯出獨立簡報，可離線開啟。請另保留課程檔供編輯。');}catch(e){notify(e.message);}};
function exportHTML(data){data=CourseWorkflow.studentView(data);const encoded=JSON.stringify(data).replace(/</g,'\\u003c'),css=M.slideCSS;
 const runtime='const deck='+encoded+';let p=Math.max(0,Math.min(deck.slides.length-1,Math.trunc(Number(location.hash.slice(1)))||0));const paint='+M.paint.toString()+';const renderElement='+M.renderElement.toString()+';function show(){paint(deck.slides[p],document.getElementById("canvas"),true);document.getElementById("count").textContent=(p+1)+" / "+deck.slides.length;document.getElementById("prev").disabled=p===0;document.getElementById("next").disabled=p===deck.slides.length-1;history.replaceState(null,"","#"+p);fit();}function fit(){const s=Math.min(innerWidth/960,(innerHeight-60)/540);document.getElementById("canvas").style.transform="scale("+s+")";document.getElementById("wrap").style.width=960*s+"px";document.getElementById("wrap").style.height=540*s+"px";}function go(d){p=Math.max(0,Math.min(deck.slides.length-1,p+d));show();}document.getElementById("prev").onclick=()=>go(-1);document.getElementById("next").onclick=()=>go(1);document.getElementById("full").onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen?.().catch(()=>{});};onresize=fit;onkeydown=e=>{if(e.key==="ArrowRight"||e.key==="PageDown"){e.preventDefault();go(1);}if(e.key==="ArrowLeft"||e.key==="PageUp"){e.preventDefault();go(-1);}};show();';
 return '<!doctype html><html lang="zh-Hans"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>課堂簡報</title><style>'+css+'body{margin:0;background:#14231c}#wrap{position:absolute;left:50%;top:calc(50% - 24px);transform:translate(-50%,-50%)}#canvas{transform-origin:top left}nav{position:fixed;bottom:12px;left:0;width:100%;text-align:center;color:white;font:14px sans-serif}nav button{padding:8px 16px;margin:0 8px;border:0;border-radius:5px;cursor:pointer}</style><div id="wrap"><div id="canvas" class="slide-canvas"></div></div><nav><button id="prev">←</button><span id="count"></span><button id="next">→</button><button id="full">⛶</button></nav><script>'+runtime+'</script></html>';
}
$('draft').onclick=()=>{if(confirm('從製作稿建立可編輯草稿。只擷取標記文字，原文完整保留在教師備註；匯入後請逐頁核對題目、答案與排版。'))$('md-file').click();};
$('md-file').onchange=async ev=>{const f=ev.target.files[0];ev.target.value='';if(!f)return;try{if(f.size>5000000)throw Error('製作稿檔案過大。');await switchDeck(importDraft(await f.text(),f.name));notify('草稿已建立；原文留在各頁教師備註，請先核對再放映。');}catch(e){notify(e.message);}};
function importDraft(text,name){const result=M.blank();result.title=name.replace(/\.md$/i,'');result.slides=[];let header=null;
 for(const line of text.split(/\r?\n/)){if(!line.trim().startsWith('|')){header=null;continue;}const cells=line.split(/(?<!\\)\|/).slice(1,-1).map(x=>x.trim());if(['頁碼','檔名','投影片畫面文字'].every(k=>cells.includes(k))){header=cells;continue;}if(!header||cells.every(c=>/^:?-+:?$/.test(c)))continue;if(cells.length!==header.length)throw Error('製作表欄位不一致，請先執行文件預檢。');const row=Object.fromEntries(header.map((h,i)=>[h,cells[i]]));const raw=row['投影片畫面文字'],title=(row['畫面主標']||'新投影片').replace(/\x60/g,'');const s=M.slide(title);s.notes='待核對匯入內容。原頁碼：'+row['頁碼']+'\n\n'+header.map(h=>h+'：'+row[h]).join('\n\n');
 const strings=[...raw.matchAll(/\x60([^\x60]+)\x60/g)].map(m=>m[1]).filter(t=>!['Khởi động','Ôn phần chuẩn bị','Mẫu câu','Hội thoại','Cách dùng','Cấu trúc'].includes(t)&&!t.startsWith('Sách giáo khoa')&&!t.startsWith('课文：'));
 const content=strings.filter((s,i)=>!(i===0&&s===title)).join('\n');if(content)s.elements.push(M.element('text',{x:40,y:125,w:880,h:350,fontSize:28,text:content}));result.slides.push(s);
 }if(!result.slides.length)throw Error('找不到 HTML 投影片製作表。');return M.validate(result);}
window.addEventListener('keydown',e=>{if($('recent').open)return;if($('presenter').open){if(['ArrowRight','PageDown'].includes(e.key)){e.preventDefault();$('next').click();}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();$('prev').click();}return;}
 const typing=e.target.matches('input,textarea,select')||e.target.isContentEditable;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();document.activeElement?.blur();$('save').click();return;}if(typing)return;
 if($('materials-dialog').open)return;
 if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undoRedo(!e.shiftKey);return;}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='y'){e.preventDefault();undoRedo(false);return;}
 if($('stage').inert)return;
 if(['Delete','Backspace'].includes(e.key)&&item()){e.preventDefault();remove();}if(item()&&!item().locked&&e.key.startsWith('Arrow')){e.preventDefault();change(()=>{const n=e.shiftKey?10:1,e1=item();e1.x=M.clamp(e1.x+({'ArrowLeft':-n,'ArrowRight':n}[e.key]||0),0,960-e1.w);e1.y=M.clamp(e1.y+({'ArrowUp':-n,'ArrowDown':n}[e.key]||0),0,540-e1.h);});}});
window.addEventListener('beforeunload',e=>{if(pending||storageFailed){e.preventDefault();e.returnValue='';}});
window.addEventListener('resize',fit);
(async()=>{try{db=await database();const active=await read('active'),saved=active&&await read(active);if(saved){deck=CourseWorkflow.migrate(M.validate(saved.deck));revisions.set(deck.id,saved.revision);const found=deck.slides.findIndex(s=>'#'+s.id===location.hash);if(found>=0)page=found;}else{deck=CourseWorkflow.newCourse();saveLocal();}$('save-status').textContent='已儲存於此瀏覽器';}catch(e){deck=CourseWorkflow.newCourse();storageFailed=true;$('save-status').textContent='請下載課程檔保存';notify('瀏覽器無法自動保存。編輯後請下載課程檔。');}render();})();
